-- DEPRECATED / UNSAFE LEGACY FILE — DO NOT RUN.
-- This filename previously contained speculative renames and partial repairs,
-- including an erroneous programs_legacy branch. It has intentionally been
-- neutralized so it cannot alter a Supabase database.
--
-- Use this reviewed sequence instead:
--   1. supabase/university_schema_preflight.sql       (read-only catalog audit)
--   2. supabase/university_schema_data_audit.sql     (read-only conflict audit)
--   3. Review docs/SUPABASE_SCHEMA_REVIEW.md and the live result sets.
--   4. Only after backup + manual review, stage/test supabase/university_schema_v2.sql.
--
-- No SQL has been run against Supabase in this task. No live table rename or
-- data migration is authorized by this file.
SELECT 'Deprecated. No changes made. See supabase/university_schema_v2.sql after preflight.' AS status;
