-- DEPRECATED / UNSAFE LEGACY FILE — DO NOT RUN.
-- This file previously RENAMED universities/scholarships to *_foreign and
-- dropped/rebuilt objects — a destructive "restore" that can break a working
-- Supabase project. It has been intentionally neutralized so it cannot alter
-- a database.
--
-- USE INSTEAD (one file, additive, idempotent, covers ALL 91 app tables):
--   supabase/full_schema.sql   →  run in Supabase SQL Editor
-- then verify with:
--   DATABASE_URL=postgresql://... npm run db:verify
--
SELECT 'Deprecated. No changes made. Run supabase/full_schema.sql instead.' AS status;
